-- Safety Checks are time/status protection, not continuous tracking.
alter table public.nightguard_safety_checks add column if not exists status text not null default 'scheduled' check(status in ('scheduled','waiting','reminded','snoozed','safe','missed','escalated','completed','expired'));
alter table public.nightguard_safety_checks add column if not exists trigger_type text not null default 'timer' check(trigger_type in ('timer','after_event','leaving_venue','arrival','recurring','geofence'));
alter table public.nightguard_safety_checks add column if not exists max_snooze_minutes smallint not null default 30 check(max_snooze_minutes between 5 and 120);
create table public.nightguard_check_contacts (check_id uuid not null references public.nightguard_safety_checks(id) on delete cascade, user_id uuid not null references public.profiles(id) on delete cascade, notify_if_missed boolean not null default true, emergency_location_only boolean not null default true, share_eta boolean not null default true, call_if_no_response boolean not null default false, primary key(check_id,user_id));
create table public.nightguard_check_events (id uuid primary key default gen_random_uuid(), check_id uuid not null references public.nightguard_safety_checks(id) on delete cascade, type text not null check(type in ('created','reminder_sent','snoozed','safe_confirmed','completed','escalated','expired','silent_wellness')), metadata jsonb not null default '{}', created_at timestamptz not null default now());
create table public.nightguard_check_reminders (id uuid primary key default gen_random_uuid(), check_id uuid not null references public.nightguard_safety_checks(id) on delete cascade, type text not null check(type in ('first','second','urgent_push','phone_prompt','contact_notification')), sent_at timestamptz not null default now());
create table public.nightguard_check_escalations (id uuid primary key default gen_random_uuid(), check_id uuid not null references public.nightguard_safety_checks(id) on delete cascade, level text not null check(level in ('low','medium','high','critical','resolved')), trigger_detail text, created_at timestamptz not null default now());
create table public.nightguard_check_templates (id uuid primary key default gen_random_uuid(), owner_id uuid references public.profiles(id) on delete cascade, name text not null, duration_minutes smallint not null check(duration_minutes between 5 and 1440), grace_minutes smallint not null default 10 check(grace_minutes between 5 and 30), max_snooze_minutes smallint not null default 30, rules jsonb not null default '{}', public boolean not null default false);
alter table public.nightguard_check_contacts enable row level security; alter table public.nightguard_check_events enable row level security; alter table public.nightguard_check_reminders enable row level security; alter table public.nightguard_check_escalations enable row level security; alter table public.nightguard_check_templates enable row level security;
create policy "check owner reads contacts" on public.nightguard_check_contacts for select to authenticated using(exists(select 1 from public.nightguard_safety_checks c join public.nightguard_sessions s on s.id=c.session_id where c.id=check_id and s.owner_id=auth.uid()));
create policy "check owner reads private audit events" on public.nightguard_check_events for select to authenticated using(exists(select 1 from public.nightguard_safety_checks c join public.nightguard_sessions s on s.id=c.session_id where c.id=check_id and s.owner_id=auth.uid()));
create policy "owned or public check templates readable" on public.nightguard_check_templates for select to authenticated using(public or owner_id=auth.uid());
-- Worker defaults: 10m grace, reminders at +0/+5/+10, contact notification at +15 thereafter; risk may compress only with configured consent.
