-- Buddy Pair extends temporary NightGuard sessions. Coordinates are client-encrypted before upload.
create table public.nightguard_buddy_invitations (id uuid primary key default gen_random_uuid(), session_id uuid not null references public.nightguard_sessions(id) on delete cascade, sender_id uuid not null references public.profiles(id) on delete cascade, recipient_id uuid not null references public.profiles(id) on delete cascade, message text not null default 'Let''s stay together tonight.', expires_at timestamptz not null default now() + interval '5 minutes', responded_at timestamptz, state text not null default 'pending' check(state in ('pending','accepted','expired','cancelled')), check(expires_at > now() - interval '30 days'));
create table public.nightguard_buddy_privacy (session_id uuid not null references public.nightguard_sessions(id) on delete cascade, user_id uuid not null references public.profiles(id) on delete cascade, share_precise_location boolean not null default true, share_battery boolean not null default true, share_eta boolean not null default true, share_arrival boolean not null default true, share_movement boolean not null default true, updated_at timestamptz not null default now(), primary key(session_id,user_id));
create table public.nightguard_buddy_locations (session_id uuid not null references public.nightguard_sessions(id) on delete cascade, user_id uuid not null references public.profiles(id) on delete cascade, encrypted_payload text not null, updated_at timestamptz not null default now(), expires_at timestamptz not null, primary key(session_id,user_id));
create table public.nightguard_meetups (id uuid primary key default gen_random_uuid(), session_id uuid not null references public.nightguard_sessions(id) on delete cascade, encrypted_location text not null, title text not null default 'Meet Here', expires_at timestamptz not null default now() + interval '30 minutes', created_at timestamptz not null default now());
create table public.nightguard_session_events (id uuid primary key default gen_random_uuid(), session_id uuid not null references public.nightguard_sessions(id) on delete cascade, type text not null check(type in ('started','joined','arrived','meetup_created','together','ended','privacy_changed','emergency')), metadata jsonb not null default '{}', created_at timestamptz not null default now());
alter table public.nightguard_buddy_invitations enable row level security; alter table public.nightguard_buddy_privacy enable row level security; alter table public.nightguard_buddy_locations enable row level security; alter table public.nightguard_meetups enable row level security; alter table public.nightguard_session_events enable row level security;
create policy "invitation sender or recipient" on public.nightguard_buddy_invitations for select to authenticated using(sender_id=auth.uid() or recipient_id=auth.uid());
create policy "recipient responds to invitation" on public.nightguard_buddy_invitations for update to authenticated using(recipient_id=auth.uid()) with check(recipient_id=auth.uid());
create policy "participants manage own buddy privacy" on public.nightguard_buddy_privacy for all to authenticated using(user_id=auth.uid()) with check(user_id=auth.uid());
create policy "participants read encrypted locations" on public.nightguard_buddy_locations for select to authenticated using(exists(select 1 from public.nightguard_session_members m where m.session_id=nightguard_buddy_locations.session_id and m.user_id=auth.uid() and m.revoked_at is null));
create policy "user writes own encrypted location" on public.nightguard_buddy_locations for all to authenticated using(user_id=auth.uid()) with check(user_id=auth.uid());
create policy "participants read meetups" on public.nightguard_meetups for select to authenticated using(exists(select 1 from public.nightguard_session_members m where m.session_id=nightguard_meetups.session_id and m.user_id=auth.uid() and m.revoked_at is null));
-- Enforce the 2–20 group session cap server-side at membership insert time.
create or replace function public.enforce_buddy_group_size() returns trigger language plpgsql as $$ begin if (select type from public.nightguard_sessions where id=new.session_id) in ('group_buddy') and (select count(*) from public.nightguard_session_members where session_id=new.session_id) >= 20 then raise exception 'Buddy Pair supports at most 20 members'; end if; return new; end $$;
create trigger nightguard_group_size before insert on public.nightguard_session_members for each row execute function public.enforce_buddy_group_size();
