-- Walk Me Home uses temporary encrypted journey updates; it never retains route history by default.
create table public.nightguard_journeys (id uuid primary key default gen_random_uuid(), owner_id uuid not null references public.profiles(id) on delete cascade, state text not null default 'created' check(state in ('created','active','paused','arrival_detected','completed','deleted','emergency')), mode text not null check(mode in ('walking','cycling','driving','ride_share','public_transport','motorcycle')), destination_label text not null, encrypted_destination text, started_at timestamptz, ended_at timestamptz, expires_at timestamptz not null, created_at timestamptz not null default now());
create table public.nightguard_journey_watchers (journey_id uuid not null references public.nightguard_journeys(id) on delete cascade, user_id uuid not null references public.profiles(id) on delete cascade, permissions jsonb not null default '{"progress":true,"eta":true,"arrival":true,"battery":true}', primary key(journey_id,user_id));
create table public.nightguard_journey_updates (journey_id uuid primary key references public.nightguard_journeys(id) on delete cascade, encrypted_payload text not null, updated_at timestamptz not null default now(), expires_at timestamptz not null);
create table public.nightguard_journey_events (id uuid primary key default gen_random_uuid(), journey_id uuid not null references public.nightguard_journeys(id) on delete cascade, type text not null check(type in ('started','left_venue','route_deviation','stopped','battery_low','destination_nearby','arrived','completed')), metadata jsonb not null default '{}', created_at timestamptz not null default now());
create table public.nightguard_journey_summaries (journey_id uuid primary key references public.nightguard_journeys(id) on delete cascade, distance_meters integer, duration_seconds integer, average_speed_mps numeric, saved_at timestamptz);
alter table public.nightguard_journeys enable row level security; alter table public.nightguard_journey_watchers enable row level security; alter table public.nightguard_journey_updates enable row level security; alter table public.nightguard_journey_events enable row level security; alter table public.nightguard_journey_summaries enable row level security;
create policy "owner or watcher reads journey" on public.nightguard_journeys for select to authenticated using(owner_id=auth.uid() or exists(select 1 from public.nightguard_journey_watchers w where w.journey_id=id and w.user_id=auth.uid()));
create policy "owner creates journey" on public.nightguard_journeys for insert to authenticated with check(owner_id=auth.uid());
create policy "watchers read temporary journey update" on public.nightguard_journey_updates for select to authenticated using(exists(select 1 from public.nightguard_journeys j where j.id=journey_id and (j.owner_id=auth.uid() or exists(select 1 from public.nightguard_journey_watchers w where w.journey_id=j.id and w.user_id=auth.uid()))));
create policy "owner writes encrypted journey update" on public.nightguard_journey_updates for all to authenticated using(exists(select 1 from public.nightguard_journeys j where j.id=journey_id and j.owner_id=auth.uid())) with check(exists(select 1 from public.nightguard_journeys j where j.id=journey_id and j.owner_id=auth.uid()));
-- Client defaults: 30m arrival radius; 15% battery alert; mode-specific deviation/stop thresholds live in the shared KMP risk engine.
