-- NightGuard stores only temporary, consented safety sessions. It is not a surveillance product.
create table public.nightguard_trusted_circles (id uuid primary key default gen_random_uuid(), owner_id uuid not null references public.profiles(id) on delete cascade, name text not null, permissions jsonb not null default '{"arrival":true,"emergency":true}', created_at timestamptz not null default now());
create table public.nightguard_circle_members (circle_id uuid not null references public.nightguard_trusted_circles(id) on delete cascade, user_id uuid not null references public.profiles(id) on delete cascade, permissions jsonb not null default '{}', primary key(circle_id,user_id));
create table public.nightguard_sessions (id uuid primary key default gen_random_uuid(), owner_id uuid not null references public.profiles(id) on delete cascade, type text not null check(type in ('buddy_pair','group_buddy','walk_home','safety_check','ride_companion','emergency')), state text not null default 'created' check(state in ('created','accepted','active','paused','extended','completed','archived','deleted','escalated')), expires_at timestamptz not null, destination_label text, consented_at timestamptz, completed_at timestamptz, created_at timestamptz not null default now(), check(expires_at > created_at));
create table public.nightguard_session_members (session_id uuid not null references public.nightguard_sessions(id) on delete cascade, user_id uuid not null references public.profiles(id) on delete cascade, role text not null check(role in ('owner','buddy','trusted_contact')), accepted_at timestamptz, revoked_at timestamptz, primary key(session_id,user_id));
create table public.nightguard_safety_checks (id uuid primary key default gen_random_uuid(), session_id uuid not null references public.nightguard_sessions(id) on delete cascade, due_at timestamptz not null, grace_ends_at timestamptz not null, response text check(response in ('safe','help','snoozed','missed')), responded_at timestamptz, check(grace_ends_at >= due_at));
create table public.nightguard_presence (session_id uuid not null references public.nightguard_sessions(id) on delete cascade, user_id uuid not null references public.profiles(id) on delete cascade, status text not null check(status in ('at_venue','walking','driving','in_ride','home','idle','offline','low_battery','emergency')), battery_percent smallint check(battery_percent between 0 and 100), updated_at timestamptz not null default now(), expires_at timestamptz not null, primary key(session_id,user_id));
create table public.nightguard_incidents (id uuid primary key default gen_random_uuid(), session_id uuid not null references public.nightguard_sessions(id) on delete cascade, owner_id uuid not null references public.profiles(id) on delete cascade, state text not null default 'open' check(state in ('open','safe_confirmed','reported','closed')), created_at timestamptz not null default now(), resolved_at timestamptz);
alter table public.nightguard_trusted_circles enable row level security; alter table public.nightguard_circle_members enable row level security; alter table public.nightguard_sessions enable row level security; alter table public.nightguard_session_members enable row level security; alter table public.nightguard_safety_checks enable row level security; alter table public.nightguard_presence enable row level security; alter table public.nightguard_incidents enable row level security;
create policy "owners manage trusted circles" on public.nightguard_trusted_circles for all to authenticated using(owner_id=auth.uid()) with check(owner_id=auth.uid());
create policy "circle members readable by owner or member" on public.nightguard_circle_members for select to authenticated using(exists(select 1 from public.nightguard_trusted_circles c where c.id=circle_id and c.owner_id=auth.uid()) or user_id=auth.uid());
create policy "session participants read sessions" on public.nightguard_sessions for select to authenticated using(owner_id=auth.uid() or exists(select 1 from public.nightguard_session_members m where m.session_id=id and m.user_id=auth.uid() and m.revoked_at is null));
create policy "owner creates sessions" on public.nightguard_sessions for insert to authenticated with check(owner_id=auth.uid());
create policy "participants read session members" on public.nightguard_session_members for select to authenticated using(exists(select 1 from public.nightguard_sessions s where s.id=session_id and (s.owner_id=auth.uid() or exists(select 1 from public.nightguard_session_members self where self.session_id=s.id and self.user_id=auth.uid() and self.revoked_at is null))));
create policy "participants read unexpired presence" on public.nightguard_presence for select to authenticated using(expires_at > now() and exists(select 1 from public.nightguard_session_members m where m.session_id=nightguard_presence.session_id and m.user_id=auth.uid() and m.revoked_at is null));
create policy "user writes own presence" on public.nightguard_presence for insert to authenticated with check(user_id=auth.uid());
create policy "participants read checks" on public.nightguard_safety_checks for select to authenticated using(exists(select 1 from public.nightguard_session_members m where m.session_id=nightguard_safety_checks.session_id and m.user_id=auth.uid() and m.revoked_at is null));
create policy "owner reads incidents" on public.nightguard_incidents for select to authenticated using(owner_id=auth.uid());
-- A scheduled worker archives sessions and deletes expired presence/location data; no raw location is retained in this schema.
